# Site settings
title: Immersive Expressions
title-bold: ACM SIGGRAPH
title-normal: Digital Arts Community
email: youremailaddress@gmail.com
description: An online digital art exhibition showcasing virtual reality on the web
# baseurl: "/webvrshow" # the subpath of your site, e.g. /blog
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
image: assets/images/banner.png
url: http://immersive-expressions.siggraph.org

exclude: [README.md]

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 0 #6

# Build settings
markdown: kramdown
