# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: ACM SIGGRAPH
title-normal: Digital Arts Community
email: youremailaddress@gmail.com
description: An online digital art exhibition showcasing virtual reality on the web
# baseurl: "/webvrshow" # the subpath of your site, e.g. /blog
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

exclude: [README.md]

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 0 #6

# Build settings
markdown: kramdown
